name: Build MkDocs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Clone repository
        run: |
          git clone --depth 1 --branch master https://git.mcarov.pro/ilyamak04/wiki.git          

      - name: Build site
        run: |
          cd wiki
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          mkdocs build          

      - name: Deploy site
        run: |
          cd wiki
          rm -rf /var/www/wiki/*
          cp -r site/ /var/www/wiki/site/          

